---
title: "Project 1 Info"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height=4, fig.width=10)
options(show.signif.stars = FALSE)
```


## Project Overview

The first course project will use a dataset of your choice to explore data visualization. For the report, you should identify a research question of interest to explore with data visualization. I'd expect at least 3 or 4 different graphics in this report.

The report should contain sections such as introduction, data overview + data visualization, and discussion. The following is a rubric that will be used to assess the report. 
All items are graded with the following scheme, where some have multipliers:

1. __No Credit__: Criterion was not addressed or was written in a way that was not understandable.

2. __Beginning__:  Ideas are not clear and supporting ideas are not presented.

3. __Developing__: Ideas are identified but not well supported and developed or are minimally supported and developed.

4. __Advanced__: Ideas are clearly identified and are adequately supported and developed.

| __Report generalities__ | __Points__  | __Multiplier__|
|:------------------------|---|---:|
|Spelling, grammar, writing clarity |   |  3 |
|Paragraphs, section labels |   | 1 |
|Appendix with complete code |   |  1 |
|Figures (reporting, labels, captions) included in text|   |  1 |
|Citations for papers and packages used |   |  1 |
|Acknowledgments for other resources |   |  1 |


| __Introduction__ | __Points__  | __Multiplier__ |
|:------------------------|---|---:|
|Project motivation |   |  1 |
|Sample size(s) |   | 1 |
|Data source and study design |   |  1 |
|Research question |   |  1 |

| __Data Overview + Data Visualization__ |  |  |
|:------------------------|---|---:|
|Variables with units and descriptive statistics |   |  1 |
|Figure Titles and Labels |   | 1 |
|Figure Captions |   | 1 |
|Figure Clarity |   | 2|
|Figure Quality |   | 2|



| __Discussion__ | __Points__  | __Multiplier__ |
|:------------------------|---|---:|
|Reframe research question |   |  1 |
|Summarize findings from data visualization |   | 1 |
|Suggestion of next directions |   | 1 |
